<a href="https://colab.research.google.com/github/tngus18/gongboohaeboza/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD_%EA%B0%80%EC%9D%B4%EB%93%9C_01_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EB%B0%98%EC%9D%98_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EA%B3%BC_%EC%83%9D%ED%83%9C%EA%B3%84%EC%9D%B4%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#파이썬과 R기반의 머신러닝 비교
- R은 통계전용 프로그램 언어
- 파이썬은 다양한 영역에서 사용되는 개발 전문 프로그램 언어

## 파이썬 머신러닝 생태계를 구성하는 주요 패키지
- 머신러닝 패키지 : 사이킷런(대표), 데이터 마이닝 기반의 머신러닝에서 독보적
- 행렬/선형대수/통계패키지 : 넘파이(행렬, 선형대수), 싸이파이(자연과학 통계를 위한 다양한 패키지)
- 데이터 핸들링 : 판다스(데이터 처리 패키지), 2차원 데이터 처리에 특화
- 시각화 : 맷플롯립, 시본


## 넘파이

In [1]:
# np.array

In [2]:
import numpy as np

In [7]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

#array1(3,) : 1차원 3원소
#array2(2,3) : 2차원 2개 줄(로우) 3원소(칼럼)
#array3(1,3) : 2차원 1개 줄 3원소

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [9]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [10]:
# ndarray 내의 데이터 타입은 dtype으로 확인 가능. 정수, 실수, 문자열 다 가능

In [11]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [15]:
list2 = [1,2,'test']
print(type(list2))
array2 = np.array(list2)
print(type(array2))
print(array2, array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U21


In [17]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [20]:
# ndarray 타입변경은 astype()매서드를 이용함.
array_int = np.array([1,2,3])
array_float= array_int.astype('float32')
array_int = array_float.astype('int32')
print(array_int, array_int.dtype)

[1 2 3] int32


-----------------------------

In [22]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [23]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [24]:
# ndarray의 차원과 크기를 변경 reshape() 숫자범위내의 지정된 사이즈로 변경 가능능
array1 = np.arange(10)
print('array:\n', array1)

array2 = array1.reshape(2,5)
print('array:\n', array2)

array3 = array1.reshape(5,2)
print('arrau:\n', array3)

array:
 [0 1 2 3 4 5 6 7 8 9]
array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arrau:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [25]:
# -1을 적어주면 원래 ndarray와 호환되는 새로운 shape으로 변환해줌.
array1 = np.arange(10)
print('array:\n', array1)

array2 = array1.reshape(-1,5)
print('array:\n', array2.shape)

array3 = array1.reshape(-1,2)
print('arrau:\n', array3.shape)

array:
 [0 1 2 3 4 5 6 7 8 9]
array:
 (2, 5)
arrau:
 (5, 2)


In [31]:
#reshape(-1,1) 를 이용해 3차원->2차원->1차원 변경 가능 
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원을 2차원으로 ndarray 변환
array5 =array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#2차원을 1차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [33]:
# 3x3 의 배열로 1-10까지 작성
array1d = np.arange(start= 1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# boolean indexing
array1d = np.arange(start=1, stop=10)
# []안에 array1d>5 boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 값:', array3)

array1d>5 불린 인덱싱 값: [6 7 8 9]


1. step1: array1d>5 와 같이 ndarray의 필터링 조건을 []안에 기재
2. step2: False값은 무시하고 True값에 해당하는 인덱스 값만 저장(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것)
3. step3: 저장된 인덱스 데이터 세트로 ndarray 조회

In [36]:
# 행렬의 정렬 - sort(), argsort()

In [39]:
org_array = np.array([3,1,9,5])
print('원본행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)

원본행렬: [3 1 9 5]


In [40]:
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_arrray.sort()호출 후 반환된 행렬:', sort_array2)
print('org_arrray.sort()호출 후 원본 행렬:', org_array)

np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_arrray.sort()호출 후 반환된 행렬: None
org_arrray.sort()호출 후 원본 행렬: [1 3 5 9]


In [41]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [42]:
# 로우방향 정렬, 칼럼방향 정렬
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis =1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [43]:
from numpy.core.fromnumeric import transpose
# 전치행렬 transpose()

A = np.array([[1,2],
              [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]


## 데이터 핸들링 - 판다스