<a href="https://colab.research.google.com/github/tngus18/gongboohaeboza/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD_%EA%B0%80%EC%9D%B4%EB%93%9C_01_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EB%B0%98%EC%9D%98_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EA%B3%BC_%EC%83%9D%ED%83%9C%EA%B3%84%EC%9D%B4%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#파이썬과 R기반의 머신러닝 비교
- R은 통계전용 프로그램 언어
- 파이썬은 다양한 영역에서 사용되는 개발 전문 프로그램 언어

## 파이썬 머신러닝 생태계를 구성하는 주요 패키지
- 머신러닝 패키지 : 사이킷런(대표), 데이터 마이닝 기반의 머신러닝에서 독보적
- 행렬/선형대수/통계패키지 : 넘파이(행렬, 선형대수), 싸이파이(자연과학 통계를 위한 다양한 패키지)
- 데이터 핸들링 : 판다스(데이터 처리 패키지), 2차원 데이터 처리에 특화
- 시각화 : 맷플롯립, 시본


## 넘파이

In [ ]:
# np.array

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

#array1(3,) : 1차원 3원소
#array2(2,3) : 2차원 2개 줄(로우) 3원소(칼럼)
#array3(1,3) : 2차원 1개 줄 3원소

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [ ]:
# ndarray 내의 데이터 타입은 dtype으로 확인 가능. 정수, 실수, 문자열 다 가능

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1,2,'test']
print(type(list2))
array2 = np.array(list2)
print(type(array2))
print(array2, array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U21


In [ ]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [ ]:
# ndarray 타입변경은 astype()매서드를 이용함.
array_int = np.array([1,2,3])
array_float= array_int.astype('float32')
array_int = array_float.astype('int32')
print(array_int, array_int.dtype)

[1 2 3] int32


-----------------------------

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [ ]:
# ndarray의 차원과 크기를 변경 reshape() 숫자범위내의 지정된 사이즈로 변경 가능능
array1 = np.arange(10)
print('array:\n', array1)

array2 = array1.reshape(2,5)
print('array:\n', array2)

array3 = array1.reshape(5,2)
print('arrau:\n', array3)

array:
 [0 1 2 3 4 5 6 7 8 9]
array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arrau:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# -1을 적어주면 원래 ndarray와 호환되는 새로운 shape으로 변환해줌.
array1 = np.arange(10)
print('array:\n', array1)

array2 = array1.reshape(-1,5)
print('array:\n', array2.shape)

array3 = array1.reshape(-1,2)
print('arrau:\n', array3.shape)

array:
 [0 1 2 3 4 5 6 7 8 9]
array:
 (2, 5)
arrau:
 (5, 2)


In [ ]:
#reshape(-1,1) 를 이용해 3차원->2차원->1차원 변경 가능 
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원을 2차원으로 ndarray 변환
array5 =array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#2차원을 1차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [ ]:
# 3x3 의 배열로 1-10까지 작성
array1d = np.arange(start= 1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# boolean indexing
array1d = np.arange(start=1, stop=10)
# []안에 array1d>5 boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 값:', array3)

array1d>5 불린 인덱싱 값: [6 7 8 9]


1. step1: array1d>5 와 같이 ndarray의 필터링 조건을 []안에 기재
2. step2: False값은 무시하고 True값에 해당하는 인덱스 값만 저장(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것)
3. step3: 저장된 인덱스 데이터 세트로 ndarray 조회

In [ ]:
# 행렬의 정렬 - sort(), argsort()

In [ ]:
org_array = np.array([3,1,9,5])
print('원본행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)

원본행렬: [3 1 9 5]


In [ ]:
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_arrray.sort()호출 후 반환된 행렬:', sort_array2)
print('org_arrray.sort()호출 후 원본 행렬:', org_array)

np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_arrray.sort()호출 후 반환된 행렬: None
org_arrray.sort()호출 후 원본 행렬: [1 3 5 9]


In [ ]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
# 로우방향 정렬, 칼럼방향 정렬
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis =1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [ ]:
from numpy.core.fromnumeric import transpose
# 전치행렬 transpose()

A = np.array([[1,2],
              [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]


## 데이터 핸들링 - 판다스

In [ ]:
import pandas as pd

In [103]:
titanic_df = pd.read_csv(r'/content/test.csv')
titanic_df.head(3)

PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q

In [104]:
titanic_df.shape   # 418개의 로우와 11개의 칼럼

(418, 11)

In [105]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [106]:
titanic_df.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [107]:
# value_counts(), 데이터 분포도를 확인하는데 매우 유용한 함수
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

3    218
1    107
2     93
Name: Pclass, dtype: int64


In [108]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
3    218
1    107
2     93
Name: Pclass, dtype: int64


In [109]:
col_name1=['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)
print('-'*50)
print('#리스트를 이용')
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFarame:\n', df_list1)
print('#넘파이 ndarray를 이용')
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarrya로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
--------------------------------------------------
#리스트를 이용
1차원 리스트로 만든 DataFarame:
    col1
0     1
1     2
2     3
#넘파이 ndarray를 이용
1차원 ndarrya로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [110]:
col_name2=['col1','col2','col3']

# 2행 3열 형태의 리스트와 ndarray 생성후 dataframe 으로 변환환
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)
print('-'*50)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFarame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarry로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
--------------------------------------------------
2차원 리스트로 만든 DataFarame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarry로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [111]:
#딕셔너리를 dataframe으로 변환
dict = {'col':[1,11],'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col  col2  col3
0    1     2     3
1   11    22    33


In [112]:
#칼럼 데이터 세트 생성과 수정

In [113]:
titanic_df['Age_0']=0
titanic_df.head(3)

PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked  Age_0
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q      0
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S      0
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q      0

In [114]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q      0      345.0          1
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S      0      470.0          2
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q      0      620.0          1

In [115]:
# DataFrame 데이터 삭제

In [116]:
titanic_drop_df = titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)


PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked  Age_by_10  Family_No
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q      345.0          1
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S      470.0          2
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q      620.0          1

In [117]:
titanic_df.head(3)

PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q      0      345.0          1
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S      0      470.0          2
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q      0      620.0          1

In [118]:
drop_result = titanic_df.drop(['Age_0','Age_by_10','Family_No'],axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 갑:', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 갑: None


PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q

In [119]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth',15)
print('### before axis 0 drop ####')
print(titanic_df.head(3))
titanic_df.drop([0,1,2], axis = 0, inplace=True)
print('#### after axis 0 drop ####')
print(titanic_df.head(3))

### before axis 0 drop ####
   PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q
#### after axis 0 drop ####
   PassengerId  Pclass            Name     Sex   Age  SibSp  Parch   Ticket     Fare Cabin Embarked
3          895       3  Wirz, Mr. A...    male  27.0      0      0   315154   8.6625   NaN        S
4          896       3  Hirvonen, M...  female  22.0      1      1  3101298  12.2875   NaN        S
5          897       3  Svensson, M...    male  14.0      0      0     7538   9.2250   NaN        S


In [120]:
#index 객체

In [122]:
#원본 파일 다시 로딩
titanic_df = pd.read_csv('/content/train.csv')
indexes = titanic_df.index
print(indexes)
print('Index객체 array값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 

In [123]:
# Series객체는 index객체를 포함하지만 series 객체에 연산 함수를 적용할 때 index는 연산에서 제외됨.

In [124]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series :', sum(series_fair))
print('Fair Series +3: \n', (series_fair+3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series : 28693.949299999967
Fair Series +3: 
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [125]:
#DataFrame 및 Series 에 reset_index()메서드 수행하면 새롭게 인덱스를 연속 숫자 형으로 할당하며 기존 인덱스는 index라는 새로운 컬럼명으로 추가
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [126]:
# reset_index()는 인덱스가 연속된 int숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 주로 사용.

In [133]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

### before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


In [134]:
# 데이터 셀렉션 및 필터링

In [135]:
# iloc[] 은 위치 기반 인덱싱만 허용
# integer 또는 integer형의 슬라이싱, 팬시 리스트 값을 입력해주어야 함.

In [137]:
data = {'Name': ['철민','은경','진웅','수빈'],
        'Year': ['2011,2016,2015,2015'],
        'Gender': ['Male','Female','Male','Male']}
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name            Year  Gender
one     철민  2011,2016,2...    Male
two     은경  2011,2016,2...  Female
three   진웅  2011,2016,2...    Male
four    수빈  2011,2016,2...    Male

In [142]:
data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns={'index': 'old_index'})
data_df_reset.index = data_df_reset.index+1
data_df_reset

old_index Name            Year  Gender
1       one   철민  2011,2016,2...    Male
2       two   은경  2011,2016,2...  Female
3     three   진웅  2011,2016,2...    Male
4      four   수빈  2011,2016,2...    Male

In [138]:
data_df.iloc[0,0]    #indexing이 아닌 명칭을 입력하면 오류 발생

'철민'

In [143]:
data_df_reset.iloc[0,1]

'철민'

In [145]:
data_df.loc['one','Name']

'철민'

In [146]:
# 정렬 aggregation, groupby

In [147]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [149]:
# 내림차순순
titanic_sorted = titanic_df.sort_values(by=['Pclass','Name'], ascending=False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

In [150]:
#aggregation

In [151]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [152]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [153]:
# groupby
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [154]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [155]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [156]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [158]:
agg_format={'Age':'max', 'SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [159]:
# 결손 데이터 처리하기

In [161]:
# isna() 결손 데이터 여부 확인
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [162]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [163]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')  # fillna -결손값 대체
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [165]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [168]:
# apply lambda 식으로 가공
def get_squre(a):
    return a**2
print('3의 제곱은:', get_squre(3))

3의 제곱은: 9


In [170]:
lambda_square = lambda x : x ** 2
print('3의 제곱은:', lambda_square(3))

# : 로 입력인자와 반환될 입력 인자의 계산식을 분리.

3의 제곱은: 9


In [171]:
a = [1,2,3]
squares = map(lambda x:x**2,a)
list(squares)


[1, 4, 9]

In [173]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [175]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

# if else를 지원하는데 if절의 경우 if식보다 반환 값을 먼저 기술해야 함.

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [178]:
# else if 를 지원하지 않기 때문에 else 안에 새로운 if를 넣어줘야 함
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df[['Age_cat']].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
dtype: int64

In [182]:
# 더 많은 함수
def get_category(age):
    cat = ''
    if age <= 5 :cat = 'Baby'
    elif age <=12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else :cat = 'Ederly'

    return cat

# lambda 식에 위에서 지정한 get_category() 함수를 반환값으로 지정

titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age','Age_cat']].head()

Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult